name: Probiotic Dog
favicon: null
layout_spectrum: 0.011017083888873458
typography_spectrum: 0.4812339402269572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5497312089428306
  lightness: 0.3211091107223183
  saturation: 0.7224406129680574
  rhythmicContrast: 0.004831432830542326
purpose: []
